version: '3.5'
services:
  proxy-nginx:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/nginx.conf:/nginx.conf
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
    networks:
      - default
      - shared-network
    restart: always

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  shared-network:
    external: true